name: 'build'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add badges
        uses: elangosundar/social-ai@master
        with:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          social-icons: 'twitter'
