name: 'build'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add social icons
        uses: elangosundar/social-ai@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          social-icons: '[ { "socialName": "twitter", "userName": "elango_sundar"}, { "socialName": "facebook", "userName": "elango_sundar"}, { "socialName": "dev-dot-to", "userName": "elango_sundar"}, { "socialName": "codesandbox", "userName": "elango_sundar"},{ "socialName": "stackoverflow", "userName": "elango_sundar"}, { "socialName": "youtube", "userName": "elango_sundar"}]'
